* Version 0.50
** Update genanki documentation.
Document new fields, add usage example to README.
Mention that deck ID is POSIX epoch second timestamp, used for
determining relative due dates of cards.
** DONE Match Wanki deck.
CLOSED: [2017-08-21 Mon]
Kanji, then vocab, then radicals. Use Anki card editor.
** DONE Support vocabulary audio and example sentences.
CLOSED: [2017-08-22 Tue 22:19]
See issue [[https://github.com/holocronweaver/wanikani2anki/issues/3][#3]].

For now this content can be obtained by scraping the site.

Since this content rarely changes and is user-independent, updates can
be done very infrequently, maybe once a year.
** Embed media and fonts.
** Support multiple card types.
These generally only apply to vocab.
Most of these can probably be configured with JS variables.
*** Japanese -> readings + meanings
Can be split to match WaniKani.
*** spoken Japanese -> readings + meanings
Due to number of homonyms, this may be useless.
*** meanings -> readings
Due to number of synonyms, this may be useless.
*** options
**** enable typing
Applies to radicals and kanji as well.
Enabled/disabled on a per-card type basis.
**** kanji separate meaning / reading
** Support mobile Anki (phone + tablet).
*** AnkiDroid
*** AnkiMobile (MacOS/iOS)
** Create web interface and core Python library.
*** Support export filters.
*** Add export filters to CLI.
* Version 1.00
** Check if scraped data can be obtained from WK API.
See issue [[https://github.com/holocronweaver/wanikani2anki/issues/3][#3]].

WaniKani API V2 is supposedly going to support vocabulary audio and
example sentences in the future. See related [[https://community.wanikani.com/t/API-V2-Alpha-Documentation/18987/67][WaniKani form post]].

Context sentences, meaning and reading mnemonics, and audio.
** Double check WaniKani SRS to Anki SRS translation.
** Ensure deck updates properly.
Need to figure out how to update Anki decks without disrupting SRS
divergence between Anki and WaniKani.
** Write documentation.
CLI, library, web frontend.
** WaniKani stats Anki addon
A simple Anki addon which produces WaniKani-style stats.
** Double check deck visuals.
Use custom study to speed up deck updates and keep cards consistent.
*** desktop (Win, Mac, Linux)
*** mobile (Android, iOS)
*** compare against Ganki (Wanki)
*** ensure media and fonts properly embedded
** Study with deck daily for 2 weeks.
