#! /usr/bin/env python3
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v2.0. If a copy of the MPL was not distributed with this
# file, you can obtain one at http://mozilla.org/MPL/2.0/.
"""A CLI for converting WaniKani user data to an Anki deck.
"""
import os

from wanikani2anki import WaniKani2Anki

wk2a = WaniKani2Anki()

options = wk2a.options

apikey = options['api key']
if not apikey:
    apikey = input('Please enter your WaniKani API V2 key (not V1!): ')
user = wk2a.get_user(apikey)

print('''Fetching information for
      user:  {username}
      level: {level}
'''.format(**user['wanikani']['data']))

try:
    data = wk2a.get_data(user)
except KeyboardInterrupt:
    print('\nDownload canceled. Exiting.')
    exit()

#TODO: Remove if CLI can't customize deck SRS. Which it probably can't.
deck_options = wk2a.create_deck_options(user)

try:
    deck = wk2a.create_deck(user, data, deck_options)
except KeyboardInterrupt:
    print('\nDeck building canceled. Exiting.')
    exit()

print('Writing deck...')
deck_path = os.path.join(user['path'], options['deck path'])
wk2a.write_deck_to_file(deck, deck_path, override=True)
print('All done.')
